name: Build kernel with KernelSU/KernelSU-Next integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  start:
    name: Build ${{ matrix.variant }}
    strategy:
      fail-fast: false
      matrix:
        variant: [KernelSU, KernelSU-Next]
        beta: [beta, stable]
    uses: ./.github/workflows/build.yml
    with: 
      variant: ${{ matrix.variant }}
      beta: ${{ matrix.beta }}
